[camera]
position = [1, 0.8, 2]
look_at = [0, 0.3, 0]
focal_length = 1

[render]
width = 1000
height = 1000
scale = 1

[[lights]]
position = [2, 2, 3]
color = [20, 18, 15]

[[lights]]
position = [-2, 2, 1]
color = [6, 8, 16]

[[lights]]
position = [0, 3, -1]
color = [8, 6, 12]

[model]
file = "./3d_files/SuzanneCubedPink.obj"
