[camera]
position = [0.5, 0.3, 2]
look_at = [0, 0, 0]
focal_length = 1

[render]
width = 400
height = 400
scale = 1.5

[[lights]]
position = [2, 1, 2]
color = [4, 3.2, 2.4]

[[lights]]
position = [-2, 0, 1]
color = [1.2, 1.6, 3.2]

[[lights]]
position = [-1, 1, -2]
color = [2, 0.8, 2.8]

[model]
file = "./3d_files/SuzanneCubed.obj"
color = [1, 0.2, 0.3]
